# Generated by Django 6.0 on 2026-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Pankaj_Kumar_', max_length=100),
        ),
    ]
