# Generated by Django 6.0 on 2026-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
